expose_php = Off
display_errors = Off
log_errors = On
error_log = /proc/self/fd/2
memory_limit = 256M
max_execution_time = 120
max_input_time = 120
post_max_size = 110M
upload_max_filesize = 100M
upload_tmp_dir = /tmp/uploads
max_file_uploads = 20
session.cookie_httponly = 1
session.cookie_secure = 1
zend.assertions = -1

opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
opcache.jit = off
